# Generated by Django 4.0.5 on 2022-06-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_follow', 'can follow teachers'),)},
        ),
    ]
