# Generated by Django 4.0.5 on 2022-06-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/', verbose_name='Фотография'),
        ),
    ]
